# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1136, 1200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 241, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.load_gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.load_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.load_gridLayout.setObjectName("load_gridLayout")
        self.load_X_ray_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.load_X_ray_button.setObjectName("load_X_ray_button")
        self.load_gridLayout.addWidget(self.load_X_ray_button, 2, 1, 1, 1)
        self.load_MRI_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.load_MRI_button.setEnabled(True)
        self.load_MRI_button.setObjectName("load_MRI_button")
        self.load_gridLayout.addWidget(self.load_MRI_button, 1, 1, 1, 1)
        self.surface_topology_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.surface_topology_button.setObjectName("surface_topology_button")
        self.load_gridLayout.addWidget(self.surface_topology_button, 4, 1, 1, 1)
        self.load_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.load_label.setFont(font)
        self.load_label.setObjectName("load_label")
        self.load_gridLayout.addWidget(self.load_label, 0, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(259, 9, 831, 631))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.graphics_gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.graphics_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.graphics_gridLayout.setObjectName("graphics_gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.gridLayoutWidget_2)
        self.graphicsView.setObjectName("graphicsView")
        self.graphics_gridLayout.addWidget(self.graphicsView, 1, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 160, 241, 71))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.registeration_button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.registeration_button.setEnabled(True)
        self.registeration_button.setObjectName("registeration_button")
        self.gridLayout_4.addWidget(self.registeration_button, 2, 1, 1, 1)
        self.registeration_lable = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.registeration_lable.setFont(font)
        self.registeration_lable.setObjectName("registeration_lable")
        self.gridLayout_4.addWidget(self.registeration_lable, 1, 1, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 250, 241, 366))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.view_gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.view_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.view_gridLayout.setObjectName("view_gridLayout")
        self.X_Ray_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.X_Ray_checkBox.setObjectName("X_Ray_checkBox")
        self.view_gridLayout.addWidget(self.X_Ray_checkBox, 1, 1, 1, 1)
        self.MRI_vertebrae_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.MRI_vertebrae_checkbox.setObjectName("MRI_vertebrae_checkbox")
        self.view_gridLayout.addWidget(self.MRI_vertebrae_checkbox, 8, 1, 1, 1)
        self.vertebral_landmark = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.vertebral_landmark.setObjectName("vertebral_landmark")
        self.view_gridLayout.addWidget(self.vertebral_landmark, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.view_gridLayout.addItem(spacerItem, 9, 1, 1, 1)
        self.registered_slices_view_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.registered_slices_view_label.setObjectName("registered_slices_view_label")
        self.view_gridLayout.addWidget(self.registered_slices_view_label, 10, 1, 1, 1)
        self.surface_t_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.surface_t_checkbox.setObjectName("surface_t_checkbox")
        self.view_gridLayout.addWidget(self.surface_t_checkbox, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.view_gridLayout.addItem(spacerItem1, 5, 1, 1, 1)
        self.View_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.View_label.setFont(font)
        self.View_label.setObjectName("View_label")
        self.view_gridLayout.addWidget(self.View_label, 0, 1, 1, 1)
        self.MRI_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MRI_spinBox.sizePolicy().hasHeightForWidth())
        self.MRI_spinBox.setSizePolicy(sizePolicy)
        self.MRI_spinBox.setObjectName("MRI_spinBox")
        self.view_gridLayout.addWidget(self.MRI_spinBox, 11, 1, 1, 1)
        self.saggital_MRI_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.saggital_MRI_checkBox.setObjectName("saggital_MRI_checkBox")
        self.view_gridLayout.addWidget(self.saggital_MRI_checkBox, 7, 1, 1, 1)
        self.MRI_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.MRI_checkBox.setObjectName("MRI_checkBox")
        self.view_gridLayout.addWidget(self.MRI_checkBox, 6, 1, 1, 1)
        self.ext_landmark_checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.ext_landmark_checkBox.setObjectName("ext_landmark_checkBox")
        self.view_gridLayout.addWidget(self.ext_landmark_checkBox, 3, 1, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 630, 241, 71))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.save_gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.save_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.save_gridLayout.setObjectName("save_gridLayout")
        self.save_button = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.save_button.setEnabled(True)
        self.save_button.setObjectName("save_button")
        self.save_gridLayout.addWidget(self.save_button, 2, 1, 1, 1)
        self.save_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.save_label.setFont(font)
        self.save_label.setObjectName("save_label")
        self.save_gridLayout.addWidget(self.save_label, 1, 1, 1, 1)
        self.render_frame = QtWidgets.QFrame(self.centralwidget)
        self.render_frame.setGeometry(QtCore.QRect(240, 649, 831, 400))
        self.render_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.render_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.render_frame.setObjectName("render_frame")
        # self.horizontalLayoutWidget = QtWidgets.QWidget(self.render_frame)
        # self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 831, 171))
        # self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        # self.render_horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        # self.render_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        # self.render_horizontalLayout.setObjectName("render_horizontalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1136, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "3DSpineVizualization"))
        self.load_X_ray_button.setText(_translate("MainWindow", "Load X-Ray"))
        self.load_MRI_button.setText(_translate("MainWindow", "Load MRI"))
        self.surface_topology_button.setText(_translate("MainWindow", "Load Surface Topology"))
        self.load_label.setText(_translate("MainWindow", "Load"))
        self.registeration_button.setText(_translate("MainWindow", "Register"))
        self.registeration_lable.setText(_translate("MainWindow", "Registration"))
        self.X_Ray_checkBox.setText(_translate("MainWindow", "X-Ray"))
        self.MRI_vertebrae_checkbox.setText(_translate("MainWindow", "MRI vertebrae"))
        self.vertebral_landmark.setText(_translate("MainWindow", "Vertebral Landmarks"))
        self.registered_slices_view_label.setText(_translate("MainWindow", "View registered slice"))
        self.surface_t_checkbox.setText(_translate("MainWindow", "Surface"))
        self.View_label.setText(_translate("MainWindow", "View"))
        self.saggital_MRI_checkBox.setText(_translate("MainWindow", "Saggital MRIs"))
        self.MRI_checkBox.setText(_translate("MainWindow", "MRI"))
        self.ext_landmark_checkBox.setText(_translate("MainWindow", "External Landmarks"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.save_label.setText(_translate("MainWindow", "Save"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))

